/**
 * AIScribe Web — API Service Client
 *
 * Central Axios instance for all browser-to-Express communication.
 * All requests go to /api/* which Vite proxies to Express on :3001
 * during local development (see vite.config.js).
 *
 * Why a shared instance?
 *   - Authorization header is injected once here, not in every component.
 *   - Base URL is configured in one place — easy to swap for production.
 *   - Response interceptors handle 401 redirects globally.
 */

import axios from 'axios';

const apiClient = axios.create({
  baseURL: '/api',
  headers: { 'Content-Type': 'application/json' },
  timeout: 35000 // 35s — covers Whisper transcription (30s) + buffer
});

// Inject Bearer token from localStorage on every request
apiClient.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('aiscribe_token');
    if (token) config.headers.Authorization = `Bearer ${token}`;
    return config;
  },
  (error) => Promise.reject(error)
);

// On 401, clear the stored token (session expired / invalid)
apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      localStorage.removeItem('aiscribe_token');
    }
    return Promise.reject(error);
  }
);

/** POST /api/auth/login */
export async function login(email, password) {
  const res = await apiClient.post('/auth/login', { email, password });
  return res.data;
}

/** GET /api/appointments — today's pending (non-Submitted) appointments */
export async function getAppointments() {
  const res = await apiClient.get('/appointments');
  return res.data;
}

/** GET /api/appointments/completed — today's Submitted appointments */
export async function getCompletedAppointments() {
  const res = await apiClient.get('/appointments/completed');
  return res.data;
}

/** POST /api/schedule/sync — manual FHIR sync for the authenticated provider */
export async function syncSchedule() {
  const res = await apiClient.post('/schedule/sync');
  return res.data;
}

/**
 * POST /api/transcribe
 * Accepts an audio file and the associated encounter context, returns a SOAP note.
 *
 * @param {File}   audioFile  — .mp3 or .wav, max 25 MB
 * @param {object} encounter  — selected encounter object (must have .csn and .mrn)
 * @returns {Promise<object>} — { transcript, soap, follow_up_scheduled, ... }
 */
export async function transcribeAudio(audioFile, encounter) {
  const form = new FormData();
  form.append('audio', audioFile);
  if (encounter?.csn) form.append('csn', encounter.csn);
  if (encounter?.mrn) form.append('mrn', encounter.mrn);

  const res = await apiClient.post('/transcribe', form, {
    headers: { 'Content-Type': 'multipart/form-data' },
    timeout: 120000  // 2 min — Whisper (~25s) + Claude (~35s) + Mirth + buffer; overrides the 35s global default
  });
  return res.data;
}

/**
 * POST /api/submit-note
 * @param {string} csn — encounter ID
 * @param {{subjective, objective, assessment, plan}} soapNote
 * @param {string} idempotencyKey — UUID4 generated by the browser
 */
export async function submitNote(csn, soapNote, idempotencyKey) {
  const res = await apiClient.post('/submit-note', { csn, soap: soapNote, idempotencyKey });
  return res.data;
}

/** GET /api/patients — all distinct patients for the authenticated provider */
export async function getPatients() {
  const res = await apiClient.get('/patients');
  return res.data;
}

/**
 * GET /api/patients/:mrn/history
 * Returns all encounters for a patient MRN scoped to the authenticated provider.
 * Enforces provider isolation — 403 if MRN is not in this provider's patient list.
 */
export async function getPatientHistory(mrn) {
  const res = await apiClient.get(`/patients/${encodeURIComponent(mrn)}/history`);
  return res.data;
}

/**
 * GET /api/notes/:csn
 * Fetch the current signed note for an encounter.
 * Checks clinical_note_versions first (is_current=TRUE), falls back to clinical_notes (v1).
 */
export async function getNote(csn) {
  const res = await apiClient.get(`/notes/${encodeURIComponent(csn)}`);
  return res.data;
}

/**
 * POST /api/notes/amend
 * Submit a clinical note amendment. Creates a new versioned row via Mirth (MDM^T04).
 * @param {string} csn
 * @param {{subjective, objective, assessment, plan}} amendedSoap
 * @param {string} amendmentReason — required non-empty reason
 * @param {string} idempotencyKey — UUID4 generated at submission time
 */
export async function amendNote(csn, amendedSoap, amendmentReason, idempotencyKey) {
  const res = await apiClient.post('/notes/amend', { csn, amendedSoap, amendmentReason, idempotencyKey });
  return res.data;
}

/** GET /api/providers/me — authenticated provider's profile + custom_prompt_template */
export async function getProviderMe() {
  const res = await apiClient.get('/providers/me');
  return res.data;
}

/**
 * POST /api/providers/me/prompt
 * Save or reset the provider's custom Claude prompt template.
 * Pass null to reset to the system default.
 */
export async function savePromptTemplate(customPromptTemplate) {
  const res = await apiClient.post('/providers/me/prompt', { customPromptTemplate });
  return res.data;
}

export default apiClient;
